const players = [{
    'id': 'tf235',
    'username': 'tf235',
    'online': false,
    'language': 'en',
    'profile': {
        'country': 'GB',
    },
    'perfs': {
        'blitz': {
            'games': 1759,
            'rating': 1563,
            'rd': 61,
            'prov': false,
            'prog': 30,
        },
        'crazyhouse': {
            'games': 9,
            'rating': 1488,
            'rd': 140,
            'prov': true,
            'prog': 0,
        },
        'bullet': {
            'games': 1079,
            'rating': 1444,
            'rd': 62,
            'prov': false,
            'prog': -24,
        },
        'correspondence': {
            'games': 1,
            'rating': 1337,
            'rd': 290,
            'prov': true,
            'prog': 0,
        },
        'puzzle': {
            'games': 790,
            'rating': 1699,
            'rd': 63,
            'prov': false,
            'prog': 19,
        },
        'classical': {
            'games': 2904,
            'rating': 1718,
            'rd': 61,
            'prov': false,
            'prog': -65,
        },
    },
    'createdAt': 1411660632569,
    'seenAt': 1492538069039,
    'url': 'https://lichess.org/@/tf235',
}, {
    'id': 'sydeman',
    'username': 'sydeman',
    'online': false,
    'language': 'en',
    'profile': {
        'country': 'GB',
    },
    'perfs': {
        'blitz': {
            'games': 2261,
            'rating': 1378,
            'rd': 61,
            'prov': false,
            'prog': 11,
        },
        'kingOfTheHill': {
            'games': 13,
            'rating': 1448,
            'rd': 116,
            'prov': true,
            'prog': 50,
        },
        'threeCheck': {
            'games': 24,
            'rating': 1608,
            'rd': 86,
            'prov': false,
            'prog': 18,
        },
        'bullet': {
            'games': 827,
            'rating': 1239,
            'rd': 61,
            'prov': false,
            'prog': 8,
        },
        'correspondence': {
            'games': 0,
            'rating': 1500,
            'rd': 350,
            'prov': true,
            'prog': 0,
        },
        'puzzle': {
            'games': 229,
            'rating': 2327,
            'rd': 65,
            'prov': false,
            'prog': 36,
        },
        'atomic': {
            'games': 9,
            'rating': 1023,
            'rd': 147,
            'prov': true,
            'prog': -235,
        },
        'classical': {
            'games': 871,
            'rating': 1586,
            'rd': 62,
            'prov': false,
            'prog': -53,
        },
        'ultraBullet': {
            'games': 1,
            'rating': 1337,
            'rd': 290,
            'prov': true,
            'prog': 0,
        },
    },
    'createdAt': 1386518646969,
    'seenAt': 1492608214265,
    'playTime': {
        'total': 1760519,
        'tv': 0,
    },
    'url': 'https://lichess.org/@/sydeman',
}, {
    'id': 'samei07',
    'username': 'samei07',
    'online': false,
    'language': 'en',
    'profile': {},
    'perfs': {
        'blitz': {
            'games': 21,
            'rating': 1489,
            'rd': 90,
            'prov': false,
            'prog': -15,
        },
        'bullet': {
            'games': 1,
            'rating': 1625,
            'rd': 255,
            'prov': true,
            'prog': 0,
        },
        'correspondence': {
            'games': 0,
            'rating': 1500,
            'rd': 350,
            'prov': true,
            'prog': 0,
        },
        'puzzle': {
            'games': 1067,
            'rating': 1623,
            'rd': 62,
            'prov': false,
            'prog': 19,
        },
        'classical': {
            'games': 337,
            'rating': 1545,
            'rd': 60,
            'prov': false,
            'prog': 5,
        },
    },
    'createdAt': 1409402415543,
    'seenAt': 1489161524350,
    'url': 'https://lichess.org/@/samei07',
}, {
    'id': 'torrlane',
    'username': 'torrlane',
    'online': false,
    'language': 'en',
    'profile': {},
    'perfs': {
        'chess960': {
            'games': 2,
            'rating': 1324,
            'rd': 238,
            'prov': true,
            'prog': 0,
        },
        'blitz': {
            'games': 1132,
            'rating': 1581,
            'rd': 66,
            'prov': false,
            'prog': 69,
        },
        'kingOfTheHill': {
            'games': 7,
            'rating': 1691,
            'rd': 155,
            'prov': true,
            'prog': 0,
        },
        'threeCheck': {
            'games': 1,
            'rating': 1347,
            'rd': 268,
            'prov': true,
            'prog': 0,
        },
        'bullet': {
            'games': 1778,
            'rating': 1423,
            'rd': 63,
            'prov': false,
            'prog': 46,
        },
        'correspondence': {
            'games': 1,
            'rating': 1437,
            'rd': 302,
            'prov': true,
            'prog': 0,
        },
        'puzzle': {
            'games': 2973,
            'rating': 1658,
            'rd': 62,
            'prov': false,
            'prog': -10,
        },
        'atomic': {
            'games': 1,
            'rating': 1499,
            'rd': 349,
            'prov': true,
            'prog': 0,
        },
        'classical': {
            'games': 91,
            'rating': 1664,
            'rd': 64,
            'prov': false,
            'prog': -6,
        },
    },
    'createdAt': 1400003667232,
    'seenAt': 1492184946602,
    'url': 'https://lichess.org/@/torrlane',
}, {
    'id': 'riciardos',
    'username': 'riciardos',
    'online': false,
    'language': 'en',
    'profile': {
        'country': 'GB',
    },
    'perfs': {
        'blitz': {
            'games': 27,
            'rating': 1245,
            'rd': 76,
            'prov': false,
            'prog': -148,
        },
        'threeCheck': {
            'games': 17,
            'rating': 1133,
            'rd': 115,
            'prov': true,
            'prog': -36,
        },
        'bullet': {
            'games': 10,
            'rating': 1156,
            'rd': 118,
            'prov': true,
            'prog': 0,
        },
        'correspondence': {
            'games': 0,
            'rating': 1500,
            'rd': 350,
            'prov': true,
            'prog': 0,
        },
        'puzzle': {
            'games': 592,
            'rating': 1658,
            'rd': 62,
            'prov': false,
            'prog': -18,
        },
        'classical': {
            'games': 79,
            'rating': 1434,
            'rd': 62,
            'prov': false,
            'prog': -49,
        },
    },
    'createdAt': 1487166555244,
    'seenAt': 1492638194697,
    'url': 'https://lichess.org/@/riciardos',
}, {
    'id': 'owennw',
    'username': 'owennw',
    'online': false,
    'language': 'en',
    'profile': {},
    'perfs': {
        'blitz': {
            'games': 134,
            'rating': 1518,
            'rd': 61,
            'prov': false,
            'prog': 0,
        },
        'crazyhouse': {
            'games': 2,
            'rating': 1383,
            'rd': 251,
            'prov': true,
            'prog': 0,
        },
        'bullet': {
            'games': 18,
            'rating': 1328,
            'rd': 88,
            'prov': false,
            'prog': 28,
        },
        'correspondence': {
            'games': 0,
            'rating': 1500,
            'rd': 350,
            'prov': true,
            'prog': 0,
        },
        'puzzle': {
            'games': 1120,
            'rating': 1624,
            'rd': 62,
            'prov': false,
            'prog': -10,
        },
        'classical': {
            'games': 431,
            'rating': 1590,
            'rd': 61,
            'prov': false,
            'prog': 25,
        },
    },
    'createdAt': 1458049776208,
    'seenAt': 1492695307432,
    'url': 'https://lichess.org/@/owennw',
}, {
    'id': 'jedrus07',
    'username': 'jedrus07',
    'online': false,
    'language': 'en',
    'profile': {
        'country': 'GB',
        'location': 'London',
    },
    'perfs': {
        'chess960': {
            'games': 2,
            'rating': 1369,
            'rd': 240,
            'prov': true,
            'prog': 0,
        },
        'blitz': {
            'games': 1091,
            'rating': 1919,
            'rd': 61,
            'prov': false,
            'prog': -23,
        },
        'crazyhouse': {
            'games': 49,
            'rating': 1793,
            'rd': 72,
            'prov': false,
            'prog': 53,
        },
        'bullet': {
            'games': 561,
            'rating': 1869,
            'rd': 60,
            'prov': false,
            'prog': 32,
        },
        'correspondence': {
            'games': 1,
            'rating': 1662,
            'rd': 290,
            'prov': true,
            'prog': 0,
        },
        'puzzle': {
            'games': 2393,
            'rating': 1979,
            'rd': 63,
            'prov': false,
            'prog': 28,
        },
        'atomic': {
            'games': 18,
            'rating': 1637,
            'rd': 126,
            'prov': true,
            'prog': 60,
        },
        'classical': {
            'games': 114,
            'rating': 2141,
            'rd': 63,
            'prov': false,
            'prog': 29,
        },
    },
    'createdAt': 1457703435591,
    'seenAt': 1492679096251,
    'playTime': {
        'total': 639866,
        'tv': 760,
    },
    'patron': true,
    'url': 'https://lichess.org/@/jedrus07',
}, {
    'id': 'jfaker',
    'username': 'jfaker',
    'online': false,
    'profile': {},
    'perfs': {
        'blitz': {
            'games': 0,
            'rating': 1500,
            'rd': 350,
            'prov': true,
            'prog': 0,
        },
        'bullet': {
            'games': 0,
            'rating': 1500,
            'rd': 350,
            'prov': true,
            'prog': 0,
        },
        'correspondence': {
            'games': 0,
            'rating': 1500,
            'rd': 350,
            'prov': true,
            'prog': 0,
        },
        'classical': {
            'games': 1,
            'rating': 1292,
            'rd': 250,
            'prov': true,
            'prog': 0,
        },
    },
    'createdAt': 1491581791131,
    'seenAt': 1491814223143,
    'url': 'https://lichess.org/@/jfaker',
}]

export default players
